### ISSUE TITLE
Better TypeScript Support

### ISSUE THREAD

**Issue by matthewchigira** [UXPin/uxpin-merge-tools#204]
This list of desired TypeScript features came from the old roadmap:

- [x] [Serialize enums property](https://github.com/UXPin/uxpin-merge-tools/issues/203)
- [x] [Serialize date property](https://github.com/UXPin/uxpin-merge-tools/issues/226)
- [ ] [Support React.forwardRef](https://github.com/UXPin/uxpin-merge-tools/issues/205)
- [x] [Support component with non inlined export statement](https://github.com/UXPin/uxpin-merge-tools/issues/245)
